//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SmartZip.rc
//
#define VS_VERSION_INFO1                2
#define IDC_CANCEL                      2
#define IDCANCEL2                       3
#define IDD_ABOUTBOX                    100
#define IDS_COL1                        101
#define IDD_OPTIONGENERAL               101
#define IDC_FILE                        102
#define IDS_COL2                        102
#define IDD_SPLITTER_DIALOG             102
#define IDC_FOLDER                      103
#define IDS_COL3                        103
#define IDC_PROGRESS                    104
#define IDS_COL4                        104
#define IDS_COL5                        105
#define IDC_VEDIO                       106
#define IDS_COL6                        106
#define IDS_COL7                        107
#define IDS_COL8                        108
#define IDS_COL9                        109
#define IDR_MAINFRAME                   128
#define IDR_SMARTZTYPE                  129
#define IDD_VERIPASS                    129
#define IDB_DBPROJECTS                  130
#define IDD_DLGOPTIONS                  130
#define IDB_FOLDER                      131
#define IDR_LCONTEXT                    132
#define IDR_TCONTEXT                    133
#define IDD_PROPERTIES                  133
#define IDR_NEWZIP                      135
#define IDD_FILERENAME                  136
#define IDD_FILEVIEW                    137
#define IDD_MYFAVORITES                 138
#define IDD_FILEPROP                    139
#define IDR_SFX1                        141
#define IDI_ZIP1                        141
#define IDR_AVIEXTRACT                  148
#define IDR_AVIDELETE                   149
#define IDR_AVITEST                     150
#define IDB_BITMAP2                     159
#define IDB_BITBAR                      160
#define IDI_DELETE                      161
#define IDI_CLOSE                       162
#define IDI_CLOSEHOT                    163
#define IDI_NEXTHOT                     164
#define IDI_NEXT                        165
#define IDI_BACKHOT                     166
#define IDI_BACK                        167
#define IDI_FINISH                      168
#define IDI_FINISHHOT                   169
#define IDB_SPLASH                      170
#define IDI_CANCEL3                     172
#define IDI_BROWSE                      204
#define IDC_VERYCOOL                    1000
#define IDC_PASSWORD                    1001
#define IDC_BUTTON1                     1002
#define IDC_EXPORT                      1002
#define IDC_FILENAME                    1003
#define IDC_COMBO1                      1003
#define IDC_BPS                         1003
#define IDC_ESTIMATE                    1004
#define IDC_DESTINATION                 1004
#define IDC_CALC                        1004
#define IDC_CHECK1                      1005
#define IDC_OUTPUT                      1005
#define IDC_BROWSE                      1006
#define IDC_MSFLEXGRID1                 1006
#define IDC_CHOOSE                      1007
#define IDC_CHECK2                      1008
#define IDC_FILESIZE                    1008
#define IDC_FILEICON                    1009
#define IDC_REMOVEFLIST                 1010
#define IDC_ADDFILES                    1012
#define IDC_LIST2                       1013
#define IDC_CFILE                       1014
#define IDC_CFOLDER                     1015
#define IDC_SHELLTREE                   1016
#define IDC_COMPRESSIONLEVEL            1018
#define IDC_FULLPATH                    1020
#define IDD_EXTRACT                     1021
#define IDD_OPTIONFILELIST              1022
#define IDD_FORMEXATRACT                1023
#define IDD_FORMEXTRACT                 1023
#define IDD_ADDFILES                    1024
#define IDD_ADDCHOOSE                   1025
#define IDC_COMBOBOXEX1                 1025
#define IDD_ADDFOLDER                   1026
#define IDC_ELAPSED                     1026
#define IDD_ADDOPTIONS                  1027
#define IDC_REMAINING                   1027
#define IDC_TO                          1028
#define IDC_FROM                        1030
#define IDC_LIST1                       1031
#define IDC_COMMENTS                    1036
#define IDC_TYPE                        1037
#define IDC_COMSIZE                     1040
#define IDC_UCOMSIZE                    1041
#define IDC_COMRATIO                    1042
#define IDC_CRC                         1045
#define IDC_MODDATE                     1046
#define IDC_ATTRIB                      1047
#define IDC_S1                          1052
#define IDC_S2                          1054
#define IDC_S4                          1056
#define IDC_S5                          1057
#define IDC_S6                          1058
#define IDC_CONTAINS                    1059
#define IDC_S3                          1060
#define IDC_SEP1                        1061
#define IDC_SEP2                        1062
#define IDC_EMAIL                       1065
#define IDC_NOF                         1066
#define IDI_ARROWDOWN                   2001
#define IDI_ARROWRIGHT                  2002
#define IDB_DOCKBAR                     2004
#define IDB_MDIICONS                    2008
#define IDR_MENUSYS                     2010
#define IDB_DOCKBAROFFICE               2019
#define IDB_BITMAP1                     2020
#define ID_VIEW_MYBAR                   32771
#define ID_LC_VIEW                      32772
#define ID_TOOLS_TIMETOGET              32772
#define ID_LC_DELETE                    32773
#define ID_TOOLS_BACKUPWIZARD           32773
#define ID_LC_EXTRACT                   32774
#define ID_FILE_CLOSEARCHIVE            32774
#define ID_LC_RENAME                    32775
#define ID_LC_PROPERTIES                32776
#define ID_TC_ADD                       32777
#define ID_TC_NEWFOLDER                 32778
#define ID_HELP_HELP                    32778
#define ID_TOOLS_EXTRACT                32779
#define ID_TOOLS_TEST                   32780
#define ID_TOOLS_CHANGE                 32781
#define ID_FILE_CREATE                  32782
#define ID_BACKUP_COMPRESSFILES         32783
#define ID_BACKUP_MYDOCUMENTS           32784
#define ID_BACKUP_WINDOWSFOLDER         32785
#define ID_BACKUP_SYSTEMFOLDER          32786
#define ID_BACKUP_OTHER                 32787
#define ID_VIEW_ARRANGESYMBOLS_BYNAME   32788
#define ID_VIEW_ARRANGESYMBOLS_BYDATE   32789
#define ID_VIEW_ARRANGESYMBOLS_BYTYPE   32790
#define ID_VIEW_ARRANGESYMBOLS_BYSIZE   32791
#define ID_VIEW_SELECTION_SELECTALL     32792
#define ID_VIEW_SELECTION_UNSELECTALL   32793
#define ID_VIEW_SELECTION_SELECTINVERSE 32794
#define ID_VIEW_SELECTION_SELECTFILETYPEUNDERCURSOR 32795
#define ID_VIEW_SELECTION_UNSELECTFILETYPEUNDERCURSOR 32796
#define ID_VIEW_SELECTION_SELECTGROUP   32797
#define ID_VIEW_SELECTION_UNSELECTGROUP 32798
#define ID_OPTIONS_CONFIGURATIONS       32799
#define ID_OPTIONS_PASSWORD             32800
#define ID_OPTIONS_SAVESETTINGSNOW      32801
#define ID_VIEW_LAYOUT_DETAILS          32802
#define ID_VIEW_LAYOUT_LIST             32803
#define ID_VIEW_LAYOUT_SMALLICON        32804
#define ID_VIEW_LAYOUT_LARGEICON        32805
#define ID_ACTION_NEWFOLDER             32806
#define ID_ACTION_COMMENTS              32807
#define ID_ACTION_ADD                   32808
#define ID_TOOLS_CTREATESFX             32809
#define ID_FILE_PROPERTIES              32810
#define ID_FILE_CREATESHORTCUT          32811
#define ID_FILE_COPYARCHIVE             32813
#define ID_FILE_MOVEARCHIVE             32814
#define ID_FILE_RENAMEARCHIVE           32815
#define ID_FILE_DELETEARCHIVE           32816
#define ID_TOOLS_COVERSION              32817
#define ID_TOOLS_STATISTICS             32818
#define ID_ACTION_EXPORT_TXT            32819
#define ID_ACTION_EXPORT_HTML           32820
#define ID_ACTION_EXPORT_XML            32821
#define ID_TC_VIEW                      32822
#define ID_TC_DELETE                    32823
#define ID_TC_EXTRACT                   32824
#define ID_TC_RENAME                    32825
#define ID_TC_PROPERTIES                32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
